using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AplicacionBlanco.Models
{
    public class BaseGEE
    {
        public List<VistasGEE> vistas;
        public List<DivisionAdministrativa> divisiones; 
        public BaseGEE()
        {
            this.vistas = new List<VistasGEE>();
            this.divisiones = new List<DivisionAdministrativa>();
            
            
            /*
            vistas.Add(new VistasGEE(id: 9911, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Comayagua", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9921, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Gracias a Dios", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9931, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Valle", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9941, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "La Paz", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9951, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Olancho", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9961, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Colón", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            */
            //vistas.Add(new VistasGEE(id: 9902, geeURL: "https://anin.users.earthengine.app/view/muestra4", comentario: "Test", nombre: "Test muestra 4 regiones", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));

            vistas.Add(new VistasGEE(id: 9901, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Atlantida", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_HONDURAS.jpg", titulo: "Departamento: Atlántida"));



            vistas.Add(new VistasGEE(id: 9002, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegohn", comentario: "", nombre: "DATAFUEGO_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_HONDURAS.jpg", titulo: "Departamento: Atlántida"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Antofagasta"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Arica y Parinacota"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Atacama"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Aysén"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Coquimbo"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de La Araucanía"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Los Lagos"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Los Ríos"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Magallanes"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de O'Higgins"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Tarapacá"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región de Valparaíso"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región del Biobío"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región del Maule"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región del Ñuble"));
            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "", titulo: "Región Metropolitana"));

            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Prueba construccion vista gee", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg", titulo: "Distrito: Belize"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Prueba construccion vista gee", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg", titulo: "Distrito: Cayo"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Prueba construccion vista gee", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg", titulo: "Distrito: Corozal"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Sin Comentarios", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg", titulo: "Distrito: Orange Walk"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Ning{un comentario", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg", titulo: "Distrito: Stann Creek"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "otro", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg", titulo: "Distrito: Toledo"));
            vistas.Add(new VistasGEE(id: 9023, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "", nombre: "DATACLIMA_Belice_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg", titulo: ""));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: ""));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Antofagasta"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Arica y Parinacota"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Atacama"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Aysén"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Coquimbo"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de La Araucanía"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Los Lagos"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Los Ríos"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Magallanes"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de O'Higgins"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Tarapacá"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región de Valparaíso"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región del Biobío"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región del Maule"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región del Ñuble"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Región Metropolitana"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: "Departamento: Alajuela"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: "Departamento: Cartago"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: "Departamento: Guanacaste"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: "Departamento: Heredia"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: "Departamento: Limón"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: "Departamento: Puntarenas"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: "Departamento: San José"));
            vistas.Add(new VistasGEE(id: 9019, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg", titulo: ""));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Ahuachapán"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Cabañas"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Chalatenango"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Cuscatlán"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: La Libertad"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: La Paz"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: La Unión"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Morazán"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: San Miguel"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: San Salvador"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: San Vicente"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Santa Ana"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Sonsonate"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: "Departamento: Usulután"));
            vistas.Add(new VistasGEE(id: 9015, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg", titulo: ""));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Alta Verapaz"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Baja Verapaz"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Chimaltenango"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Chiquimula"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: El Progreso"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Escuintla"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Guatemala"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Huehuetenango"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Izabal"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Jalapa"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Jutiapa"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Petén"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Quetzaltenango"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Quiché"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Retalhuleu"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Sacatepéquez"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: San Marcos"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Santa Rosa"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Sololá"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Suchitepéquez"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Totonicapán"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: "Departamento: Zacapa"));
            vistas.Add(new VistasGEE(id: 9007, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg", titulo: ""));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Atlántida"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Choluteca"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Colón"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Comayagua"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Copán"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Cortés"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: El Paraiso"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Francisco Morazán"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Gracias a Dios"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Intibucá"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Islas de La Bahía"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: La Paz"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Lempira"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Ocotepeque"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Olancho"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Santa Bárbara"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Valle"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Departamento: Yoro"));
            vistas.Add(new VistasGEE(id: 9003, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: ""));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Boaco"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Carazo"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Chinandega"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Chontales"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Estelí"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Granada"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Jinotega"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: León"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Madriz"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Managua"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Masaya"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Matagalpa"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Nueva Segovia"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Río San Juan"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Departamento: Rivas"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Región Autónoma de la Costa Caribe Norte"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: "Región Autónoma de la Costa Caribe Sur"));
            vistas.Add(new VistasGEE(id: 9027, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg", titulo: ""));
            vistas.Add(new VistasGEE(id: 9011, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: ""));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Comarca Emberá Wounaán"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Comarca Kuna Yala"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Comarca Ngäbe Buglé"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Bocas del Toro"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Chiriquí"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Coclé"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Colón"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Darién"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Herrera"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Los Santos"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Panamá"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Panamá Oeste"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg", titulo: "Provincia: Veraguas"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: ""));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: AZUA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: BAORUCO"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: BARAHONA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: DAJABÓN"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: DISTRITO NACIONAL"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: DUARTE"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: EL SEIBO"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: ELÍAS PIÑA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: ESPAILLAT"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: HATO MAYOR"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: HERMANAS MIRABAL"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: INDEPENDENCIA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: LA ALTAGRACIA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: LA ROMANA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: LA VEGA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: MARÍA TRINIDAD SÁNCHEZ"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: MONSEÑOR NOUEL"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: MONTE CRISTI"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: MONTE PLATA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: PEDERNALES"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: PERAVIA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: PUERTO PLATA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SAMANÁ"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SAN CRISTÓBAL"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SAN JOSÉ DE OCOA"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SAN JUAN"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SAN PEDRO DE MACORÍS"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SANCHEZ RAMÍREZ"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SANTIAGO"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SANTIAGO RODRÍGUEZ"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: SANTO DOMINGO"));
            vistas.Add(new VistasGEE(id: 0, geeURL: "", comentario: "", nombre: "", urlImagen: "", titulo: "Provincia: VALVERDE"));
            vistas.Add(new VistasGEE(id: 12345, geeURL: "https://anin.users.earthengine.app/view/dataclimabz", comentario: "", nombre: "", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg", titulo: "Test Belice"));

            divisiones.Add(new DivisionAdministrativa(id: 3, id2: 1, nombreAdministrativo: "Región de Tarapacá", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 3, id2: 0, nombreAdministrativo: "Nacional", pais: "Chile"));

        }
    }
}