using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AplicacionBlanco.Models
{
    public class BaseGEE
    {
        public List<VistasGEE> vistas;
        public List<DivisionAdministrativa> divisiones; 
        public BaseGEE()
        {
            this.vistas = new List<VistasGEE>();
            this.divisiones = new List<DivisionAdministrativa>();


            /*
            vistas.Add(new VistasGEE(id: 9911, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Comayagua", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9921, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Gracias a Dios", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9931, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Valle", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9941, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "La Paz", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9951, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Olancho", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            vistas.Add(new VistasGEE(id: 9961, geeURL: "https://anin.users.earthengine.app/view/muestra3", comentario: "Test", nombre: "Colón", urlImagen: "ImpactosDelHuracanETAenHonduras.jpg"));
            */
            vistas.Add(new VistasGEE(id: 12345, geeURL: "https://anin.users.earthengine.app/view/muestra4", comentario: "Test", nombre: "Test muestra 4 regiones", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/portadaPowerBi_DataAGRO_GeomaticaAgricola_CHILE.jpg"));

            vistas.Add(new VistasGEE(id: 9029, geeURL: "https://omarorellanahn.users.earthengine.app/view/dataagro", comentario: "", nombre: "Geomática_Agrícola_Chile_Región", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/portadaPowerBi_DataAGRO_GeomaticaAgricola_CHILE.jpg"));
            vistas.Add(new VistasGEE(id: 9021, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegobz", comentario: "", nombre: "DATAFUEGO_Belice_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_BELICE.jpg"));
            vistas.Add(new VistasGEE(id: 9022, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegobz", comentario: "", nombre: "DATAFUEGO_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_BELICE.jpg"));
            vistas.Add(new VistasGEE(id: 9017, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegocr", comentario: "", nombre: "DATAFUEGO_Costa Rica_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_COSTARICA.jpg"));
            vistas.Add(new VistasGEE(id: 9018, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegocr", comentario: "", nombre: "DATAFUEGO_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_COSTARICA.jpg"));
            vistas.Add(new VistasGEE(id: 9013, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegoes", comentario: "", nombre: "DATAFUEGO_El Salvador_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_ELSALVADOR.jpg"));
            vistas.Add(new VistasGEE(id: 9014, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegoes", comentario: "", nombre: "DATAFUEGO_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_ELSALVADOR.jpg"));
            vistas.Add(new VistasGEE(id: 9005, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegogt", comentario: "", nombre: "DATAFUEGO_Guatemala_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_GUATEMALA.jpg"));
            vistas.Add(new VistasGEE(id: 9006, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegogt", comentario: "", nombre: "DATAFUEGO_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_GUATEMALA.jpg"));
            vistas.Add(new VistasGEE(id: 9001, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegohn", comentario: "", nombre: "DATAFUEGO_Honduras_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_HONDURAS.jpg"));
            vistas.Add(new VistasGEE(id: 9002, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegohn", comentario: "", nombre: "DATAFUEGO_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_HONDURAS.jpg"));
            vistas.Add(new VistasGEE(id: 9025, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegonc", comentario: "", nombre: "DATAFUEGO_Nicaragua_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_NICARAGUA.jpg"));
            vistas.Add(new VistasGEE(id: 9026, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegonc", comentario: "", nombre: "DATAFUEGO_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_NICARAGUA.jpg"));
            vistas.Add(new VistasGEE(id: 9009, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegopn", comentario: "", nombre: "DATAFUEGO_Panamá_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_PANAMA.jpg"));
            vistas.Add(new VistasGEE(id: 9010, geeURL: "https://app-data-i.users.earthengine.app/view/datafuegopn", comentario: "", nombre: "DATAFUEGO_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATAFUEGO/portadaPowerBi_DataRIESGO_PlataformaDeAnalisisYMonitoreoDeFocosDeFuego_PANAMA.jpg"));
            vistas.Add(new VistasGEE(id: 9023, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "", nombre: "DATACLIMA_Belice_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Prueba construccion vista gee", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Sin Comentarios", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "Ning{un comentario", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg"));
            vistas.Add(new VistasGEE(id: 9024, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimabz", comentario: "otro", nombre: "DATACLIMA_Belice_Distrito", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_BELICE.jpg"));
            vistas.Add(new VistasGEE(id: 9019, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg"));
            vistas.Add(new VistasGEE(id: 9020, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimacr", comentario: "", nombre: "DATACLIMA_Costa Rica_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_COSTARICA.jpg"));
            vistas.Add(new VistasGEE(id: 9015, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg"));
            vistas.Add(new VistasGEE(id: 9016, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimaes", comentario: "", nombre: "DATACLIMA_El Salvador_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_ELSALVADOR.jpg"));
            vistas.Add(new VistasGEE(id: 9007, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg"));
            vistas.Add(new VistasGEE(id: 9008, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimagt", comentario: "", nombre: "DATACLIMA_Guatemala_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_GUATEMALA.jpg"));
            vistas.Add(new VistasGEE(id: 9003, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg"));
            vistas.Add(new VistasGEE(id: 9004, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimahn", comentario: "", nombre: "DATACLIMA_Honduras_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_HONDURAS.jpg"));
            vistas.Add(new VistasGEE(id: 9027, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg"));
            vistas.Add(new VistasGEE(id: 9028, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimanc", comentario: "", nombre: "DATACLIMA_Nicaragua_Departamento", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_NICARAGUA.jpg"));
            vistas.Add(new VistasGEE(id: 9011, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Nacional", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg"));
            vistas.Add(new VistasGEE(id: 9012, geeURL: "https://app-data-i.users.earthengine.app/view/dataclimapn", comentario: "", nombre: "DATACLIMA_Panamá_Provincia", urlImagen: "https://raw.githubusercontent.com/Sud-Austral/DATA-COMUN/master/00%20Portadas/DATACLIMA/portadaPowerBi_DataCLIMA_PlataformaDeAnalisisYMonitoreoDelClima_PANAMA.jpg"));

            divisiones.Add(new DivisionAdministrativa(id: 23, id2: 0, nombreAdministrativo: "Nacional", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 1, nombreAdministrativo: "Departamento: Atlántida", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 2, nombreAdministrativo: "Departamento: Colón", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 3, nombreAdministrativo: "Departamento: Comayagua", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 4, nombreAdministrativo: "Departamento: Copán", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 5, nombreAdministrativo: "Departamento: Cortés", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 6, nombreAdministrativo: "Departamento: Choluteca", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 7, nombreAdministrativo: "Departamento: El Paraiso", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 8, nombreAdministrativo: "Departamento: Francisco Morazán", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 9, nombreAdministrativo: "Departamento: Gracias a Dios", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 10, nombreAdministrativo: "Departamento: Intibucá", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 11, nombreAdministrativo: "Departamento: Islas de La Bahía", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 12, nombreAdministrativo: "Departamento: La Paz", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 13, nombreAdministrativo: "Departamento: Lempira", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 14, nombreAdministrativo: "Departamento: Ocotepeque", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 15, nombreAdministrativo: "Departamento: Olancho", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 16, nombreAdministrativo: "Departamento: Santa Bárbara", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 17, nombreAdministrativo: "Departamento: Valle", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 24, id2: 18, nombreAdministrativo: "Departamento: Yoro", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 25, id2: 0, nombreAdministrativo: "Nacional", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 1, nombreAdministrativo: "Departamento: Atlántida", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 2, nombreAdministrativo: "Departamento: Colón", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 3, nombreAdministrativo: "Departamento: Comayagua", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 4, nombreAdministrativo: "Departamento: Copán", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 5, nombreAdministrativo: "Departamento: Cortés", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 6, nombreAdministrativo: "Departamento: Choluteca", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 7, nombreAdministrativo: "Departamento: El Paraiso", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 8, nombreAdministrativo: "Departamento: Francisco Morazán", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 9, nombreAdministrativo: "Departamento: Gracias a Dios", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 10, nombreAdministrativo: "Departamento: Intibucá", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 11, nombreAdministrativo: "Departamento: Islas de La Bahía", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 12, nombreAdministrativo: "Departamento: La Paz", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 13, nombreAdministrativo: "Departamento: Lempira", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 14, nombreAdministrativo: "Departamento: Ocotepeque", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 15, nombreAdministrativo: "Departamento: Olancho", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 16, nombreAdministrativo: "Departamento: Santa Bárbara", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 17, nombreAdministrativo: "Departamento: Valle", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 26, id2: 18, nombreAdministrativo: "Departamento: Yoro", pais: "Honduras"));
            divisiones.Add(new DivisionAdministrativa(id: 27, id2: 0, nombreAdministrativo: "Nacional", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 1, nombreAdministrativo: "Departamento: Guatemala", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 2, nombreAdministrativo: "Departamento: El Progreso", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 3, nombreAdministrativo: "Departamento: Sacatepéquez", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 4, nombreAdministrativo: "Departamento: Chimaltenango", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 5, nombreAdministrativo: "Departamento: Escuintla", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 6, nombreAdministrativo: "Departamento: Santa Rosa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 7, nombreAdministrativo: "Departamento: Sololá", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 8, nombreAdministrativo: "Departamento: Totonicapán", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 9, nombreAdministrativo: "Departamento: Quetzaltenango", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 10, nombreAdministrativo: "Departamento: Suchitepéquez", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 11, nombreAdministrativo: "Departamento: Retalhuleu", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 12, nombreAdministrativo: "Departamento: San Marcos", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 13, nombreAdministrativo: "Departamento: Huehuetenango", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 14, nombreAdministrativo: "Departamento: Quiché", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 15, nombreAdministrativo: "Departamento: Baja Verapaz", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 16, nombreAdministrativo: "Departamento: Alta Verapaz", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 17, nombreAdministrativo: "Departamento: Petén", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 18, nombreAdministrativo: "Departamento: Izabal", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 19, nombreAdministrativo: "Departamento: Zacapa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 20, nombreAdministrativo: "Departamento: Chiquimula", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 21, nombreAdministrativo: "Departamento: Jalapa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 28, id2: 22, nombreAdministrativo: "Departamento: Jutiapa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 29, id2: 0, nombreAdministrativo: "Nacional", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 1, nombreAdministrativo: "Departamento: Guatemala", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 2, nombreAdministrativo: "Departamento: El Progreso", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 3, nombreAdministrativo: "Departamento: Sacatepéquez", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 4, nombreAdministrativo: "Departamento: Chimaltenango", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 5, nombreAdministrativo: "Departamento: Escuintla", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 6, nombreAdministrativo: "Departamento: Santa Rosa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 7, nombreAdministrativo: "Departamento: Sololá", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 8, nombreAdministrativo: "Departamento: Totonicapán", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 9, nombreAdministrativo: "Departamento: Quetzaltenango", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 10, nombreAdministrativo: "Departamento: Suchitepéquez", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 11, nombreAdministrativo: "Departamento: Retalhuleu", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 12, nombreAdministrativo: "Departamento: San Marcos", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 13, nombreAdministrativo: "Departamento: Huehuetenango", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 14, nombreAdministrativo: "Departamento: Quiché", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 15, nombreAdministrativo: "Departamento: Baja Verapaz", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 16, nombreAdministrativo: "Departamento: Alta Verapaz", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 17, nombreAdministrativo: "Departamento: Petén", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 18, nombreAdministrativo: "Departamento: Izabal", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 19, nombreAdministrativo: "Departamento: Zacapa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 20, nombreAdministrativo: "Departamento: Chiquimula", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 21, nombreAdministrativo: "Departamento: Jalapa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 30, id2: 22, nombreAdministrativo: "Departamento: Jutiapa", pais: "Guatemala"));
            divisiones.Add(new DivisionAdministrativa(id: 31, id2: 0, nombreAdministrativo: "Nacional", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 1, nombreAdministrativo: "Provincia: Bocas del Toro", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 2, nombreAdministrativo: "Provincia: Coclé", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 3, nombreAdministrativo: "Provincia: Colón", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 4, nombreAdministrativo: "Provincia: Chiriquí", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 5, nombreAdministrativo: "Provincia: Darién", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 6, nombreAdministrativo: "Provincia: Herrera", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 7, nombreAdministrativo: "Provincia: Los Santos", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 8, nombreAdministrativo: "Provincia: Panamá", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 9, nombreAdministrativo: "Provincia: Veraguas", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 10, nombreAdministrativo: "Comarca Kuna Yala", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 11, nombreAdministrativo: "Comarca Emberá Wounaán", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 12, nombreAdministrativo: "Comarca Ngäbe Buglé", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 32, id2: 13, nombreAdministrativo: "Provincia: Panamá Oeste", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 33, id2: 0, nombreAdministrativo: "Nacional", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 1, nombreAdministrativo: "Provincia: Bocas del Toro", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 2, nombreAdministrativo: "Provincia: Coclé", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 3, nombreAdministrativo: "Provincia: Colón", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 4, nombreAdministrativo: "Provincia: Chiriquí", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 5, nombreAdministrativo: "Provincia: Darién", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 6, nombreAdministrativo: "Provincia: Herrera", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 7, nombreAdministrativo: "Provincia: Los Santos", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 8, nombreAdministrativo: "Provincia: Panamá", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 9, nombreAdministrativo: "Provincia: Veraguas", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 10, nombreAdministrativo: "Comarca Kuna Yala", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 11, nombreAdministrativo: "Comarca Emberá Wounaán", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 12, nombreAdministrativo: "Comarca Ngäbe Buglé", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 34, id2: 13, nombreAdministrativo: "Provincia: Panamá Oeste", pais: "Panamá"));
            divisiones.Add(new DivisionAdministrativa(id: 35, id2: 0, nombreAdministrativo: "Nacional", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 1, nombreAdministrativo: "Departamento: Ahuachapán", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 2, nombreAdministrativo: "Departamento: Santa Ana", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 3, nombreAdministrativo: "Departamento: Sonsonate", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 4, nombreAdministrativo: "Departamento: Chalatenango", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 5, nombreAdministrativo: "Departamento: La Libertad", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 6, nombreAdministrativo: "Departamento: San Salvador", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 7, nombreAdministrativo: "Departamento: Cuscatlán", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 8, nombreAdministrativo: "Departamento: La Paz", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 9, nombreAdministrativo: "Departamento: Cabañas", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 10, nombreAdministrativo: "Departamento: San Vicente", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 11, nombreAdministrativo: "Departamento: Usulután", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 12, nombreAdministrativo: "Departamento: San Miguel", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 13, nombreAdministrativo: "Departamento: Morazán", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 36, id2: 14, nombreAdministrativo: "Departamento: La Unión", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 37, id2: 0, nombreAdministrativo: "Nacional", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 1, nombreAdministrativo: "Departamento: Ahuachapán", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 2, nombreAdministrativo: "Departamento: Santa Ana", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 3, nombreAdministrativo: "Departamento: Sonsonate", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 4, nombreAdministrativo: "Departamento: Chalatenango", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 5, nombreAdministrativo: "Departamento: La Libertad", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 6, nombreAdministrativo: "Departamento: San Salvador", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 7, nombreAdministrativo: "Departamento: Cuscatlán", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 8, nombreAdministrativo: "Departamento: La Paz", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 9, nombreAdministrativo: "Departamento: Cabañas", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 10, nombreAdministrativo: "Departamento: San Vicente", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 11, nombreAdministrativo: "Departamento: Usulután", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 12, nombreAdministrativo: "Departamento: San Miguel", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 13, nombreAdministrativo: "Departamento: Morazán", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 38, id2: 14, nombreAdministrativo: "Departamento: La Unión", pais: "El Salvador"));
            divisiones.Add(new DivisionAdministrativa(id: 39, id2: 0, nombreAdministrativo: "Nacional", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 40, id2: 1, nombreAdministrativo: "Provincia: San José", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 40, id2: 2, nombreAdministrativo: "Provincia: Alajuela", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 40, id2: 3, nombreAdministrativo: "Provincia: Cartago", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 40, id2: 4, nombreAdministrativo: "Provincia: Heredia", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 40, id2: 5, nombreAdministrativo: "Provincia: Guanacaste", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 40, id2: 6, nombreAdministrativo: "Provincia: Puntarenas", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 40, id2: 7, nombreAdministrativo: "Provincia: Limón", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 41, id2: 0, nombreAdministrativo: "Nacional", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 42, id2: 1, nombreAdministrativo: "Provincia: San José", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 42, id2: 2, nombreAdministrativo: "Provincia: Alajuela", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 42, id2: 3, nombreAdministrativo: "Provincia: Cartago", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 42, id2: 4, nombreAdministrativo: "Provincia: Heredia", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 42, id2: 5, nombreAdministrativo: "Provincia: Guanacaste", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 42, id2: 6, nombreAdministrativo: "Provincia: Puntarenas", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 42, id2: 7, nombreAdministrativo: "Provincia: Limón", pais: "Costa Rica"));
            divisiones.Add(new DivisionAdministrativa(id: 43, id2: 0, nombreAdministrativo: "Nacional", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 44, id2: 1, nombreAdministrativo: "Distrito: Belize", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 44, id2: 2, nombreAdministrativo: "Distrito: Cayo", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 44, id2: 3, nombreAdministrativo: "Distrito: Corozal", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 44, id2: 4, nombreAdministrativo: "Distrito: Orange Walk", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 44, id2: 5, nombreAdministrativo: "Distrito: Stann Creek", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 44, id2: 6, nombreAdministrativo: "Distrito: Toledo", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 45, id2: 0, nombreAdministrativo: "Nacional", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 46, id2: 1, nombreAdministrativo: "Distrito: Belize", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 46, id2: 2, nombreAdministrativo: "Distrito: Cayo", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 46, id2: 3, nombreAdministrativo: "Distrito: Corozal", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 46, id2: 4, nombreAdministrativo: "Distrito: Orange Walk", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 46, id2: 5, nombreAdministrativo: "Distrito: Stann Creek", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 46, id2: 6, nombreAdministrativo: "Distrito: Toledo", pais: "Belice"));
            divisiones.Add(new DivisionAdministrativa(id: 47, id2: 0, nombreAdministrativo: "Nacional", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 109, nombreAdministrativo: "Provincia: Espaillat", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 118, nombreAdministrativo: "Provincia: Puerto Plata", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 125, nombreAdministrativo: "Provincia: Santiago", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 213, nombreAdministrativo: "Provincia: La Vega", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 224, nombreAdministrativo: "Provincia: Sanchez Ramírez", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 228, nombreAdministrativo: "Provincia: Monseñor Nouel", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 306, nombreAdministrativo: "Provincia: Duarte", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 314, nombreAdministrativo: "Provincia: María Trinidad Sánchez", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 319, nombreAdministrativo: "Provincia: Hermanas Mirabal", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 320, nombreAdministrativo: "Provincia: Samaná", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 405, nombreAdministrativo: "Provincia: Dajabón", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 415, nombreAdministrativo: "Provincia: Monte Cristi", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 426, nombreAdministrativo: "Provincia: Santiago Rodríguez", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 427, nombreAdministrativo: "Provincia: Valverde", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 502, nombreAdministrativo: "Provincia: Azua", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 517, nombreAdministrativo: "Provincia: Peravia", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 521, nombreAdministrativo: "Provincia: San Cristóbal", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 531, nombreAdministrativo: "Provincia: San José de Ocoa", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 603, nombreAdministrativo: "Provincia: Baoruco", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 604, nombreAdministrativo: "Provincia: Barahona", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 610, nombreAdministrativo: "Provincia: Independencia", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 616, nombreAdministrativo: "Provincia: Pedernales", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 707, nombreAdministrativo: "Provincia: Elías Piña", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 722, nombreAdministrativo: "Provincia: San Juan", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 808, nombreAdministrativo: "Provincia: El Seibo", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 811, nombreAdministrativo: "Provincia: La Altagracia", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 812, nombreAdministrativo: "Provincia: La Romana", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 923, nombreAdministrativo: "Provincia: San Pedro de Macorís", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 929, nombreAdministrativo: "Provincia: Monte Plata", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 930, nombreAdministrativo: "Provincia: Hato Mayor", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 1001, nombreAdministrativo: "Provincia: Distrito Nacional", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 48, id2: 1032, nombreAdministrativo: "Provincia: Santo Domingo", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 49, id2: 0, nombreAdministrativo: "Nacional", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 109, nombreAdministrativo: "Provincia: Espaillat", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 118, nombreAdministrativo: "Provincia: Puerto Plata", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 125, nombreAdministrativo: "Provincia: Santiago", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 213, nombreAdministrativo: "Provincia: La Vega", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 224, nombreAdministrativo: "Provincia: Sanchez Ramírez", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 228, nombreAdministrativo: "Provincia: Monseñor Nouel", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 306, nombreAdministrativo: "Provincia: Duarte", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 314, nombreAdministrativo: "Provincia: María Trinidad Sánchez", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 319, nombreAdministrativo: "Provincia: Hermanas Mirabal", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 320, nombreAdministrativo: "Provincia: Samaná", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 405, nombreAdministrativo: "Provincia: Dajabón", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 415, nombreAdministrativo: "Provincia: Monte Cristi", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 426, nombreAdministrativo: "Provincia: Santiago Rodríguez", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 427, nombreAdministrativo: "Provincia: Valverde", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 502, nombreAdministrativo: "Provincia: Azua", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 517, nombreAdministrativo: "Provincia: Peravia", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 521, nombreAdministrativo: "Provincia: San Cristóbal", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 531, nombreAdministrativo: "Provincia: San José de Ocoa", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 603, nombreAdministrativo: "Provincia: Baoruco", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 604, nombreAdministrativo: "Provincia: Barahona", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 610, nombreAdministrativo: "Provincia: Independencia", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 616, nombreAdministrativo: "Provincia: Pedernales", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 707, nombreAdministrativo: "Provincia: Elías Piña", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 722, nombreAdministrativo: "Provincia: San Juan", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 808, nombreAdministrativo: "Provincia: El Seibo", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 811, nombreAdministrativo: "Provincia: La Altagracia", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 812, nombreAdministrativo: "Provincia: La Romana", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 923, nombreAdministrativo: "Provincia: San Pedro de Macorís", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 929, nombreAdministrativo: "Provincia: Monte Plata", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 930, nombreAdministrativo: "Provincia: Hato Mayor", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 1001, nombreAdministrativo: "Provincia: Distrito Nacional", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 50, id2: 1032, nombreAdministrativo: "Provincia: Santo Domingo", pais: "Rep Dominicana"));
            divisiones.Add(new DivisionAdministrativa(id: 51, id2: 0, nombreAdministrativo: "Nacional", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 1, nombreAdministrativo: "Región de Tarapacá", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 2, nombreAdministrativo: "Región de Antofagasta", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 3, nombreAdministrativo: "Región de Atacama", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 4, nombreAdministrativo: "Región de Coquimbo", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 5, nombreAdministrativo: "Región de Valparaíso", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 6, nombreAdministrativo: "Región de O'Higgins", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 7, nombreAdministrativo: "Región del Maule", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 8, nombreAdministrativo: "Región del Biobío", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 9, nombreAdministrativo: "Región de La Araucanía", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 10, nombreAdministrativo: "Región de Los Lagos", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 11, nombreAdministrativo: "Región de Aysén", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 12, nombreAdministrativo: "Región de Magallanes", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 13, nombreAdministrativo: "Región Metropolitana", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 14, nombreAdministrativo: "Región de Los Ríos", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 15, nombreAdministrativo: "Región de Arica y Parinacota", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 52, id2: 16, nombreAdministrativo: "Región del Ñuble", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 53, id2: 0, nombreAdministrativo: "Nacional", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 1, nombreAdministrativo: "Región de Tarapacá", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 2, nombreAdministrativo: "Región de Antofagasta", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 3, nombreAdministrativo: "Región de Atacama", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 4, nombreAdministrativo: "Región de Coquimbo", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 5, nombreAdministrativo: "Región de Valparaíso", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 6, nombreAdministrativo: "Región de O'Higgins", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 7, nombreAdministrativo: "Región del Maule", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 8, nombreAdministrativo: "Región del Biobío", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 9, nombreAdministrativo: "Región de La Araucanía", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 10, nombreAdministrativo: "Región de Los Lagos", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 11, nombreAdministrativo: "Región de Aysén", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 12, nombreAdministrativo: "Región de Magallanes", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 13, nombreAdministrativo: "Región Metropolitana", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 14, nombreAdministrativo: "Región de Los Ríos", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 15, nombreAdministrativo: "Región de Arica y Parinacota", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 54, id2: 16, nombreAdministrativo: "Región del Ñuble", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 55, id2: 0, nombreAdministrativo: "Nacional", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 5, nombreAdministrativo: "Departamento: Nueva Segovia", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 10, nombreAdministrativo: "Departamento: Jinotega", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 20, nombreAdministrativo: "Departamento: Madriz", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 25, nombreAdministrativo: "Departamento: Estelí", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 30, nombreAdministrativo: "Departamento: Chinandega", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 35, nombreAdministrativo: "Departamento: León", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 40, nombreAdministrativo: "Departamento: Matagalpa", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 50, nombreAdministrativo: "Departamento: Boaco", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 55, nombreAdministrativo: "Departamento: Managua", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 60, nombreAdministrativo: "Departamento: Masaya", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 65, nombreAdministrativo: "Departamento: Chontales", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 70, nombreAdministrativo: "Departamento: Granada", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 75, nombreAdministrativo: "Departamento: Carazo", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 80, nombreAdministrativo: "Departamento: Rivas", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 85, nombreAdministrativo: "Departamento: Río San Juan", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 91, nombreAdministrativo: "Región Autónoma de la Costa Caribe Norte", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 56, id2: 93, nombreAdministrativo: "Región Autónoma de la Costa Caribe Sur", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 57, id2: 0, nombreAdministrativo: "Nacional", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 5, nombreAdministrativo: "Departamento: Nueva Segovia", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 10, nombreAdministrativo: "Departamento: Jinotega", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 20, nombreAdministrativo: "Departamento: Madriz", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 25, nombreAdministrativo: "Departamento: Estelí", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 30, nombreAdministrativo: "Departamento: Chinandega", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 35, nombreAdministrativo: "Departamento: León", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 40, nombreAdministrativo: "Departamento: Matagalpa", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 50, nombreAdministrativo: "Departamento: Boaco", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 55, nombreAdministrativo: "Departamento: Managua", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 60, nombreAdministrativo: "Departamento: Masaya", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 65, nombreAdministrativo: "Departamento: Chontales", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 70, nombreAdministrativo: "Departamento: Granada", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 75, nombreAdministrativo: "Departamento: Carazo", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 80, nombreAdministrativo: "Departamento: Rivas", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 85, nombreAdministrativo: "Departamento: Río San Juan", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 91, nombreAdministrativo: "Región Autónoma de la Costa Caribe Norte", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 58, id2: 93, nombreAdministrativo: "Región Autónoma de la Costa Caribe Sur", pais: "Nicaragua"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Antofagasta", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Arica y Parinacota", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Atacama", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Aysén", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Coquimbo", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de La Araucanía", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Los Lagos", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Los Ríos", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Magallanes", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de O'Higgins", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Tarapacá", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región de Valparaíso", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región del Biobío", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región del Maule", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región del Ñuble", pais: "Chile"));
            divisiones.Add(new DivisionAdministrativa(id: 64, id2: 0, nombreAdministrativo: "Región Metropolitana", pais: "Chile"));
            



        }
    }
}