//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AplicacionBlanco.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class graficosEntities : DbContext
    {
        public graficosEntities()
            : base("name=graficosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<DETALLE> DETALLE { get; set; }
        public virtual DbSet<FUENTE> FUENTE { get; set; }
        public virtual DbSet<GRAFICO> GRAFICO { get; set; }
        public virtual DbSet<INDUSTRIA> INDUSTRIA { get; set; }
        public virtual DbSet<PARAMETRO> PARAMETRO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<RESPONSABLE> RESPONSABLE { get; set; }
        public virtual DbSet<SECTOR> SECTOR { get; set; }
        public virtual DbSet<TEMPORALIDAD> TEMPORALIDAD { get; set; }
        public virtual DbSet<TERRITORIO> TERRITORIO { get; set; }
        public virtual DbSet<TIPO_GRAFICO> TIPO_GRAFICO { get; set; }
    }
}
